title = "42 Dev Diaries"
baseURL = "http://example.org/"
languageCode = "en-us"
theme = "ananke"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "42 Dev Diaries"
    weight = 1
    contentDir = "content/en"
  [languages.pt]
    title = "Diario Dev da 42"
    weight = 2
    contentDir = "content/pt"

[sitemap]
  changefreq = "daily"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = "Daily blog posts about my progress on 42 S Paulo."
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/librity/ft_dev_diaries"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/luis-geniole-b2b22aba/"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-gray"
  featured_image = "/images/ft_s_paulo.jpg"
  recent_posts_number = 2
